import { Col, Row, Anchor, Card, Checkbox, Button } from "antd";
import "./chooseBills.css";

const { Link } = Anchor;

const ChooseBills = () => {
  return (
    <>
      <div className="jeevan" style={{}}>
        <div className="head" style={{}}>
          <h1 className={false} style={{}}>
            Choose up to 5 bills.
          </h1>
          <p className={false} style={{}}>
            Which bills would you like to pay?
          </p>
        </div>
        <div className={false} style={{}}>
          <Card
            className={"classname"}
            style={{}}
            bordered={true}
            hoverable={false}
            loading={false}
            size={"default"}
          >
            <Row
              className={"classname"}
              style={{}}
              align={"top"}
              gutter={"0"}
              justify={"start"}
              wrap={false}
            >
              <Col
                className={"classname"}
                style={{}}
                span={4}
                order={"0"}
                offset={"0"}
                push={"0"}
                pull={"0"}
                xs={"0"}
                sm={"0"}
                md={"0"}
                lg={"0"}
                xl={"0"}
                xxl={"0"}
              >
                LOGO 1
              </Col>
              <Col
                className={"classname"}
                style={{}}
                span={12}
                order={"0"}
                offset={"0"}
                push={"0"}
                pull={"0"}
                xs={"0"}
                sm={"0"}
                md={"0"}
                lg={"0"}
                xl={"0"}
                xxl={"0"}
              >
                <h3 className={false} style={{}}>
                  Test Biller 1 ..ruru
                </h3>
                <p className={false} style={{}}>
                  Ebill 1
                </p>
                <p className={false} style={{}}>
                  Due May 1
                </p>
              </Col>
              <Col
                className={"classname"}
                style={{}}
                span={6}
                order={"0"}
                offset={"0"}
                push={"0"}
                pull={"0"}
                xs={"0"}
                sm={"0"}
                md={"0"}
                lg={"0"}
                xl={"0"}
                xxl={"0"}
              >
                <h5>$250.50</h5>
              </Col>
              <Col
                className={"classname"}
                style={{}}
                span={4}
                order={"0"}
                offset={"0"}
                push={"0"}
                pull={"0"}
                xs={"0"}
                sm={"0"}
                md={"0"}
                lg={"0"}
                xl={"0"}
                xxl={"0"}
              >
                <Checkbox
                  className="checkbox"
                  style={{}}
                  autoFocus={false}
                  checked={false}
                  defaultChecked={false}
                  disabled={false}
                  intermediate={false}
                ></Checkbox>
              </Col>
            </Row>
          </Card>
        </div>
        <div className={false} style={{}}>
          <Card
            className={"classname"}
            style={{}}
            bordered={true}
            hoverable={false}
            loading={false}
            size={"default"}
          >
            <Row
              className={"classname"}
              style={{}}
              align={"top"}
              gutter={"0"}
              justify={"start"}
              wrap={false}
            >
              <Col
                className={"classname"}
                style={{}}
                span={4}
                order={"0"}
                offset={"0"}
                push={"0"}
                pull={"0"}
                xs={"0"}
                sm={"0"}
                md={"0"}
                lg={"0"}
                xl={"0"}
                xxl={"0"}
              >
                LOGO 1
              </Col>
              <Col
                className={"classname"}
                style={{}}
                span={12}
                order={"0"}
                offset={"0"}
                push={"0"}
                pull={"0"}
                xs={"0"}
                sm={"0"}
                md={"0"}
                lg={"0"}
                xl={"0"}
                xxl={"0"}
              >
                <h3 className={false} style={{}}>
                  Test Biller 1 ..ruru
                </h3>
                <p className={false} style={{}}>
                  Ebill 1
                </p>
                <p className={false} style={{}}>
                  Due May 1
                </p>
              </Col>
              <Col
                className={"classname"}
                style={{}}
                span={6}
                order={"0"}
                offset={"0"}
                push={"0"}
                pull={"0"}
                xs={"0"}
                sm={"0"}
                md={"0"}
                lg={"0"}
                xl={"0"}
                xxl={"0"}
              >
                <h5>$250.50</h5>
              </Col>
              <Col
                className={"classname"}
                style={{}}
                span={4}
                order={"0"}
                offset={"0"}
                push={"0"}
                pull={"0"}
                xs={"0"}
                sm={"0"}
                md={"0"}
                lg={"0"}
                xl={"0"}
                xxl={"0"}
              >
                <Checkbox
                  className="checkbox"
                  style={{}}
                  autoFocus={false}
                  checked={false}
                  defaultChecked={false}
                  disabled={false}
                  intermediate={false}
                ></Checkbox>
              </Col>
            </Row>
          </Card>
        </div>
        <div className={false} style={{}}>
          <Card
            className={"classname"}
            style={{}}
            bordered={true}
            hoverable={false}
            loading={false}
            size={"default"}
          >
            <Row
              className={"classname"}
              style={{}}
              align={"top"}
              gutter={"0"}
              justify={"start"}
              wrap={false}
            >
              <Col
                className={"classname"}
                style={{}}
                span={4}
                order={"0"}
                offset={"0"}
                push={"0"}
                pull={"0"}
                xs={"0"}
                sm={"0"}
                md={"0"}
                lg={"0"}
                xl={"0"}
                xxl={"0"}
              >
                LOGO 1
              </Col>
              <Col
                className={"classname"}
                style={{}}
                span={12}
                order={"0"}
                offset={"0"}
                push={"0"}
                pull={"0"}
                xs={"0"}
                sm={"0"}
                md={"0"}
                lg={"0"}
                xl={"0"}
                xxl={"0"}
              >
                <h3 className={false} style={{}}>
                  Test Biller 1 ..ruru
                </h3>
                <p className={false} style={{}}>
                  Ebill 1
                </p>
                <p className={false} style={{}}>
                  Due May 1
                </p>
              </Col>
              <Col
                className={"classname"}
                style={{}}
                span={6}
                order={"0"}
                offset={"0"}
                push={"0"}
                pull={"0"}
                xs={"0"}
                sm={"0"}
                md={"0"}
                lg={"0"}
                xl={"0"}
                xxl={"0"}
              >
                <h5>$250.50</h5>
              </Col>
              <Col
                className={"classname"}
                style={{}}
                span={4}
                order={"0"}
                offset={"0"}
                push={"0"}
                pull={"0"}
                xs={"0"}
                sm={"0"}
                md={"0"}
                lg={"0"}
                xl={"0"}
                xxl={"0"}
              >
                <Checkbox
                  className="checkbox"
                  style={{}}
                  autoFocus={false}
                  checked={false}
                  defaultChecked={false}
                  disabled={false}
                  intermediate={false}
                ></Checkbox>
              </Col>
            </Row>
          </Card>
        </div>
        <div className={false} style={{}}>
          <Card
            className={"classname"}
            style={{}}
            bordered={true}
            hoverable={false}
            loading={false}
            size={"default"}
          >
            <Row
              className={"classname"}
              style={{}}
              align={"top"}
              gutter={"0"}
              justify={"start"}
              wrap={false}
            >
              <Col
                className={"classname"}
                style={{}}
                span={4}
                order={"0"}
                offset={"0"}
                push={"0"}
                pull={"0"}
                xs={"0"}
                sm={"0"}
                md={"0"}
                lg={"0"}
                xl={"0"}
                xxl={"0"}
              >
                LOGO 1
              </Col>
              <Col
                className={"classname"}
                style={{}}
                span={12}
                order={"0"}
                offset={"0"}
                push={"0"}
                pull={"0"}
                xs={"0"}
                sm={"0"}
                md={"0"}
                lg={"0"}
                xl={"0"}
                xxl={"0"}
              >
                <h3 className={false} style={{}}>
                  Test Biller 1 ..ruru
                </h3>
                <p className={false} style={{}}>
                  Ebill 1
                </p>
                <p className={false} style={{}}>
                  Due May 1
                </p>
              </Col>
              <Col
                className={"classname"}
                style={{}}
                span={6}
                order={"0"}
                offset={"0"}
                push={"0"}
                pull={"0"}
                xs={"0"}
                sm={"0"}
                md={"0"}
                lg={"0"}
                xl={"0"}
                xxl={"0"}
              >
                <h5>$250.50</h5>
              </Col>
              <Col
                className={"classname"}
                style={{}}
                span={4}
                order={"0"}
                offset={"0"}
                push={"0"}
                pull={"0"}
                xs={"0"}
                sm={"0"}
                md={"0"}
                lg={"0"}
                xl={"0"}
                xxl={"0"}
              >
                <Checkbox
                  className="checkbox"
                  style={{}}
                  autoFocus={false}
                  checked={false}
                  defaultChecked={false}
                  disabled={false}
                  intermediate={false}
                ></Checkbox>
              </Col>
            </Row>
          </Card>
        </div>

        <div className={false} style={{}}>
          <Row
            className={"classname"}
            style={{}}
            align={"top"}
            gutter={"0"}
            justify={"start"}
            wrap={false}
          >
            <Col
              className={"classname"}
              style={{}}
              span={15}
              order={"0"}
              offset={"0"}
              push={"0"}
              pull={"0"}
              xs={"0"}
              sm={"0"}
              md={"0"}
              lg={"0"}
              xl={"0"}
              xxl={"0"}
            ></Col>
            <Col
              className={"classname"}
              style={{}}
              span={6}
              order={"0"}
              offset={"0"}
              push={"0"}
              pull={"0"}
              xs={"0"}
              sm={"0"}
              md={"0"}
              lg={"0"}
              xl={"0"}
              xxl={"0"}
            >
              <Button
                className="button"
                style={{}}
                block={false}
                danger={false}
                disabled={false}
                ghost={false}
                htmlType={"button"}
                loading={false}
                size={"middle"}
                type={"default"}
              >
                Cancel
              </Button>
            </Col>
            <Col
              className={"classname"}
              style={{}}
              span={6}
              order={"0"}
              offset={"0"}
              push={"0"}
              pull={"0"}
              xs={"0"}
              sm={"0"}
              md={"0"}
              lg={"0"}
              xl={"0"}
              xxl={"0"}
            >
              <Button
                className="button"
                style={{}}
                block={false}
                danger={false}
                disabled={false}
                ghost={false}
                htmlType={"button"}
                loading={false}
                size={"middle"}
                type={"primary"}
              >
                Next
              </Button>
            </Col>
          </Row>
        </div>
      </div>
    </>
  );
};

export default ChooseBills;
